//! `crypto` namespace method descriptors.

use crate::builtins::*;

pub const SPEC: &[BuiltinMethod] = &[
    BuiltinMethod {
        namespace: "crypto",
        name: "sha224",
        method_id: 0,
        params: &[BuiltinParam {
            name: "data",
            ty: TySpec::Str,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the SHA-224 hex digest of a string.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "sha256",
        method_id: 1,
        params: &[BuiltinParam {
            name: "data",
            ty: TySpec::Str,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the SHA-256 hex digest of a string.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "sha384",
        method_id: 2,
        params: &[BuiltinParam {
            name: "data",
            ty: TySpec::Str,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the SHA-384 hex digest of a string.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "sha512",
        method_id: 3,
        params: &[BuiltinParam {
            name: "data",
            ty: TySpec::Str,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the SHA-512 hex digest of a string.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "sha512_224",
        method_id: 4,
        params: &[BuiltinParam {
            name: "data",
            ty: TySpec::Str,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the SHA-512/224 hex digest of a string.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "sha512_256",
        method_id: 5,
        params: &[BuiltinParam {
            name: "data",
            ty: TySpec::Str,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the SHA-512/256 hex digest of a string.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "hmac_sha224",
        method_id: 6,
        params: &[
            BuiltinParam {
                name: "key",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
            BuiltinParam {
                name: "data",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
        ],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the HMAC-SHA-224 hex digest.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "hmac_sha256",
        method_id: 7,
        params: &[
            BuiltinParam {
                name: "key",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
            BuiltinParam {
                name: "data",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
        ],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the HMAC-SHA-256 hex digest.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "hmac_sha384",
        method_id: 8,
        params: &[
            BuiltinParam {
                name: "key",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
            BuiltinParam {
                name: "data",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
        ],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the HMAC-SHA-384 hex digest.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "hmac_sha512",
        method_id: 9,
        params: &[
            BuiltinParam {
                name: "key",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
            BuiltinParam {
                name: "data",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
        ],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the HMAC-SHA-512 hex digest.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "hmac_sha512_224",
        method_id: 10,
        params: &[
            BuiltinParam {
                name: "key",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
            BuiltinParam {
                name: "data",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
        ],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the HMAC-SHA-512/224 hex digest.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "hmac_sha512_256",
        method_id: 11,
        params: &[
            BuiltinParam {
                name: "key",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
            BuiltinParam {
                name: "data",
                ty: TySpec::Str,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
        ],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Return the HMAC-SHA-512/256 hex digest.",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "token",
        method_id: 12,
        params: &[BuiltinParam {
            name: "bytes",
            ty: TySpec::Int,
            optional: true,
            binding: ParamBinding::Either,
        }],
        result: BuiltinResult::Fixed(TySpec::Str),
        doc: "Generate a random URL-safe token of the given byte length (default 32).",
    },
    BuiltinMethod {
        namespace: "crypto",
        name: "random_bytes",
        method_id: 13,
        params: &[BuiltinParam {
            name: "len",
            ty: TySpec::Int,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::ListOfInt),
        doc: "Generate cryptographically random bytes as a list of integers.",
    },
];
