//! `math` namespace method descriptors.

use crate::builtins::*;

pub const SPEC: &[BuiltinMethod] = &[
    BuiltinMethod {
        namespace: "math",
        name: "PI",
        method_id: 0,
        params: &[],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "The mathematical constant π (3.14159…).",
    },
    BuiltinMethod {
        namespace: "math",
        name: "E",
        method_id: 1,
        params: &[],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "The mathematical constant e (2.71828…).",
    },
    BuiltinMethod {
        namespace: "math",
        name: "sqrt",
        method_id: 2,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the square root of x.",
    },
    BuiltinMethod {
        namespace: "math",
        name: "pow",
        method_id: 3,
        params: &[
            BuiltinParam {
                name: "x",
                ty: TySpec::Float,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
            BuiltinParam {
                name: "y",
                ty: TySpec::Float,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
        ],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return x raised to the power y.",
    },
    BuiltinMethod {
        namespace: "math",
        name: "exp",
        method_id: 4,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return e raised to the power x.",
    },
    BuiltinMethod {
        namespace: "math",
        name: "log",
        method_id: 5,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the natural logarithm of x.",
    },
    BuiltinMethod {
        namespace: "math",
        name: "log2",
        method_id: 6,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the base-2 logarithm of x.",
    },
    BuiltinMethod {
        namespace: "math",
        name: "log10",
        method_id: 7,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the base-10 logarithm of x.",
    },
    BuiltinMethod {
        namespace: "math",
        name: "sin",
        method_id: 8,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the sine of x (x in radians).",
    },
    BuiltinMethod {
        namespace: "math",
        name: "cos",
        method_id: 9,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the cosine of x (x in radians).",
    },
    BuiltinMethod {
        namespace: "math",
        name: "tan",
        method_id: 10,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the tangent of x (x in radians).",
    },
    BuiltinMethod {
        namespace: "math",
        name: "asin",
        method_id: 11,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the arcsine of x in radians.",
    },
    BuiltinMethod {
        namespace: "math",
        name: "acos",
        method_id: 12,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the arccosine of x in radians.",
    },
    BuiltinMethod {
        namespace: "math",
        name: "atan",
        method_id: 13,
        params: &[BuiltinParam {
            name: "x",
            ty: TySpec::Float,
            optional: false,
            binding: ParamBinding::PositionalOnly,
        }],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the arctangent of x in radians.",
    },
    BuiltinMethod {
        namespace: "math",
        name: "atan2",
        method_id: 14,
        params: &[
            BuiltinParam {
                name: "y",
                ty: TySpec::Float,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
            BuiltinParam {
                name: "x",
                ty: TySpec::Float,
                optional: false,
                binding: ParamBinding::PositionalOnly,
            },
        ],
        result: BuiltinResult::Fixed(TySpec::Float),
        doc: "Return the four-quadrant arctangent of y and x in radians.",
    },
];
