# This file is regenerated by .github/workflows/release.yml on every tag.
# Before the first binary release, it serves as a placeholder so the
# `brew install --formula https://keel-lang.dev/keel.rb` command doesn't 404.
#
# Until a release exists, install from source:
#   cargo install --path .
class Keel < Formula
  desc "A programming language where AI agents are first-class citizens (alpha)"
  homepage "https://github.com/keel-lang/keel"
  license "MIT"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/keel-lang/keel/releases/download/v0.1.0/keel-aarch64-apple-darwin.tar.gz"
      # sha256 written by the release workflow on the first tag
    end
    on_intel do
      url "https://github.com/keel-lang/keel/releases/download/v0.1.0/keel-x86_64-apple-darwin.tar.gz"
      # sha256 written by the release workflow on the first tag
    end
  end

  on_linux do
    url "https://github.com/keel-lang/keel/releases/download/v0.1.0/keel-x86_64-unknown-linux-gnu.tar.gz"
    # sha256 written by the release workflow on the first tag
  end

  def install
    bin.install "keel"
  end

  test do
    system "#{bin}/keel", "--version"
  end
end
